openapi: 3.0.3
info:
  title: OpenAPI schema for kubernetes namespace creation template .
components:
  schemas:
    variables:
      type: object
      required:
      - namespace_name
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          x-walrus-ui:
            group: Basic
            order: 2
      x-walrus-ui:
        groupOrder:
        - Basic
